# Generated by Django 5.0.6 on 2024-09-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='b',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='c',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='d',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='e',
        ),
    ]
