# Generated by Django 5.0 on 2023-12-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="سوال")),
                ("option1", models.CharField(max_length=20, verbose_name="گزینه 1")),
                ("option2", models.CharField(max_length=20, verbose_name="گزینه 2")),
                ("option3", models.CharField(max_length=20, verbose_name="گزینه 3")),
                ("option4", models.CharField(max_length=20, verbose_name="گزینه 4")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="فعال / غیرفعال"),
                ),
                ("is_delete", models.BooleanField(verbose_name="حذف شده / نشده")),
            ],
        ),
    ]
