# Generated by Django 5.0 on 2023-12-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "question_App",
            "0002_questioncategorymodel_alter_questionmodel_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionmodel",
            old_name="brand",
            new_name="category",
        ),
    ]
