# Generated by Django 5.0 on 2023-12-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question_App", "0003_rename_brand_questionmodel_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questioncategorymodel",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
    ]
