# Generated by Django 5.0 on 2023-12-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_App", "0004_alter_questioncategorymodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionmodel",
            name="correct_answer",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                max_length=1,
                null=True,
                verbose_name="گرینه ی صحیح",
            ),
        ),
    ]
