# Generated by Django 5.0 on 2024-01-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_App", "0005_questionmodel_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionmodel",
            name="option1",
            field=models.CharField(max_length=200, verbose_name="گزینه 1"),
        ),
        migrations.AlterField(
            model_name="questionmodel",
            name="option2",
            field=models.CharField(max_length=200, verbose_name="گزینه 2"),
        ),
        migrations.AlterField(
            model_name="questionmodel",
            name="option3",
            field=models.CharField(max_length=200, verbose_name="گزینه 3"),
        ),
        migrations.AlterField(
            model_name="questionmodel",
            name="option4",
            field=models.CharField(max_length=200, verbose_name="گزینه 4"),
        ),
    ]
