# Generated by Django 5.0 on 2024-01-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_App", "0007_alter_questionmodel_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionmodel",
            name="seen",
            field=models.BooleanField(default=False, verbose_name="دیده شده"),
        ),
    ]
