# Generated by Django 5.0 on 2023-12-30 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ability",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="توانایی های کاربر",
                    ),
                ),
                (
                    "favorite",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="علاقه های کاربر",
                    ),
                ),
                (
                    "review",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="ارزیابی کلی",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_person",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "بررسی شخصیتی",
                "verbose_name_plural": "بررسی های شخصیت ها",
            },
        ),
    ]
